#old tests
#python train.py --data-train '/eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v6/MVA-training/ttbb_2l_dilep-bjet_delphes-met30-njet4p-btag2p/TTTT_MS/TTTT_MS.root' --data-config    FourFermion/data/ak8_points_pf_full_weighttest_Lena.yaml --network-config FourFermion/networks/particle_net_genjetAK8_weighttest_Lena.py --model-prefix TTTT_MS_mean_ctt_epochs-20_hs1-80_hs2-45_hsc-5_ParticleNet-5_300_15_2 --batch-size 100  --start-lr 1e-4 --num-epochs 100 --optimizer ranger --log FourFermion/logs/train1_ctt.log --regression-mode --weighting --tensorboard train1_ctt --gpus "" --load-epoch -1
#python train.py --data-train '/eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v6/MVA-training/ttbb_2l_dilep-bjet_delphes-met30-njet4p-btag2p/TTTT_MS/TTTT_MS.root' --data-config  FourFermion/data/ak8_points_pf_full_weighttest_Lena.yaml --network-config FourFermion/networks/particle_net_genjetAK8_weighttest_Lena.py --model-prefix TTTT_MS_mean_ctt_epochs-20_hs1-80_hs2-45_hsc-5_ParticleNet-5_30_30_20 --batch-size 100  --start-lr 1e-4 --num-epochs 1000 --optimizer ranger --log FourFermion/logs/train2_ctt.log --regression-mode --weighting --tensorboard train2_ctt --gpus "" --load-epoch 272
#python train.py --data-train '/eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v6/MVA-training/ttbb_2l_dilep-bjet_delphes-met30-njet4p-btag2p/TTTT_MS/TTTT_MS.root' --data-config  FourFermion/data/ak8_points_pf_full_weighttest_Lena.yaml --network-config FourFermion/networks/particle_net_genjetAK8_weighttest_Lena1.py --model-prefix TTTT_MS_mean_ctt_epochs-20_hs1-80_hs2-45_hsc-5_ParticleNet-5_10_10 --batch-size 100  --start-lr 1e-4 --num-epochs 1000 --optimizer ranger --log FourFermion/logs/train3_ctt.log --regression-mode --weighting --tensorboard train3_ctt --gpus "" #--load-epoch 272
#python train.py --data-train '/eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v6/MVA-training/ttbb_2l_dilep-bjet_delphes-met30-njet4p-btag2p/TTTT_MS/TTTT_MS.root' --data-config  FourFermion/data/ak8_points_pf_full_weighttest_Lena.yaml --network-config FourFermion/networks/particle_net_genjetAK8_weighttest_Lena.py --model-prefix TTTT_MS_mean_ctt_epochs-20_hs1-80_hs2-45_hsc-5_ParticleNet-5_300_30_30_20 --batch-size 100  --start-lr 1e-4 --num-epochs 1000 --optimizer ranger --log FourFermion/logs/train4_ctt.log --regression-mode --weighting --tensorboard train4_ctt --gpus "" #--load-epoch 272
#python train.py --data-train '/eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v6/MVA-training/ttbb_2l_dilep-bjet_delphes-met30-njet4p-btag2p/TTTT_MS/TTTT_MS.root' --data-config  FourFermion/data/ak8_points_pf_full_weighttest_Lena.yaml --network-config FourFermion/networks/particle_net_genjetAK8_weighttest_Lena1.py --model-prefix TTTT_MS_mean_ctt_epochs-20_hs1-80_hs2-45_hsc-5_ParticleNet-5_10_10 --batch-size 100  --start-lr 1e-4 --num-epochs 1000 --optimizer ranger --log FourFermion/logs/train3_ctt.log --regression-mode --weighting --tensorboard train3_ctt --gpus "" --load-epoch 115
# python train.py --data-train '/eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v6/MVA-training/ttbb_2l_dilep-bjet_delphes-met30-njet4p-btag2p/TTTT_MS/TTTT_MS.root' --data-config  FourFermion/data/ak8_points_pf_full_weighttest_Lena.yaml --network-config FourFermion/networks/particle_net_genjetAK8_weighttest_Lena.py --model-prefix TTTT_MS_mean_ctt_epochs-20_hs1-80_hs2-45_hsc-5_ParticleNet-5_300_30 --batch-size 10000 --start-lr 1e-2 --num-epochs 50 --optimizer adam --tensorboard "./pNet" --steps-per-epoch 100 --log FourFermion/logs/train5_ctt.log --regression-mode --weighting --in-memory --fetch-by-files --fetch-step 10 --gpus "" --load-epoch 23
# python train.py --data-train '/eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v6/MVA-training/ttbb_2l_dilep-bjet_delphes-met30-njet4p-btag2p/TTTT_MS/TTTT_MS.root' --data-config  FourFermion/data/ak8_points_pf_full_weighttest_Lena.yaml --network-config FourFermion/networks/particle_net_genjetAK8_weighttest_Lena.py --model-prefix TTTT_MS_mean_ctt_hs1-80_hs2-45_hsc-5_ParticleNet-5_10_30 --batch-size 10000 --start-lr 1e-2 --num-epochs 1000 --optimizer adam --tensorboard "./pNet_nobatchnorm" --steps-per-epoch 100 --log FourFermion/logs/train6_ctt.log --regression-mode --weighting --in-memory --fetch-by-files --fetch-step 10 --gpus "" --load-epoch 49
python train.py --data-train '/eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v6/MVA-training/ttbb_2l_dilep-bjet_delphes-met30-njet4p-btag2p/TTTT_MS/TTTT_MS.root' --data-config  FourFermion/data/ak8_points_pf_full_weighttest_Lena.yaml --network-config FourFermion/networks/particle_net_genjetAK8_weighttest_Lena1.py --model-prefix TTTT_MS_mean_ctt_hs1-80_hs2-45_hsc-5_noPN_lr4 --batch-size 10000 --start-lr 1e-4 --num-epochs 1000 --optimizer adam --tensorboard "./pNet_noPN_lr4" --steps-per-epoch 100 --log FourFermion/logs/train14_ctt.log --regression-mode --weighting --gpus "" --in-memory --fetch-by-files --fetch-step 10  #--load-epoch 49
# python train.py --data-train '/eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v6/MVA-training/ttbb_2l_dilep-bjet_delphes-met30-njet4p-btag2p/TTTT_MS/TTTT_MS.root' --data-config  FourFermion/data/ak8_points_pf_full_weighttest_Lena.yaml --network-config FourFermion/networks/particle_net_genjetAK8_weighttest_Lena2.py --model-prefix TTTT_MS_mean_ctt_hs1-80_hs2-45_hsc-5_ParticleNet-5_20_10_10 --batch-size 10000 --start-lr 1e-2 --num-epochs 1000 --optimizer adam --tensorboard "./pNet_2convlayers" --steps-per-epoch 100 --log FourFermion/logs/train8_ctt.log --regression-mode --weighting --in-memory --fetch-by-files --fetch-step 10 --gpus "" --load-epoch 49
# python train.py --data-train '/eos/vbc/group/cms/lena.wild/tttt/training-ntuples-tttt_v6/MVA-training/ttbb_2l_dilep-bjet_delphes-met30-njet4p-btag2p/TTTT_MS/TTTT_MS.root' --data-config  FourFermion/data/ak8_points_pf_full_weighttest_Lena.yaml --network-config FourFermion/networks/particle_net_genjetAK8_weighttest_Lena3.py --model-prefix TTTT_MS_mean_ctt_hs1-80_hs2-45_hsc-50_20_10 --batch-size 10000 --start-lr 1e-2 --num-epochs 1000 --optimizer adam --tensorboard "./pNet_noPN_50" --steps-per-epoch 100 --log FourFermion/logs/train11_ctt.log --regression-mode --weighting --in-memory --fetch-by-files --fetch-step 10 --gpus "" #--load-epoch 49

