python train.py \
    --data-train '/scratch-cbe/users/robert.schoefbeck/HadronicSMEFT/postprocessed/gen/v6/tschRefPointNoWidthRW/tschRefPointNoWidthRW_70.root'\
    --data-test  '/scratch-cbe/users/robert.schoefbeck/HadronicSMEFT/postprocessed/gen/v6/tschRefPointNoWidthRW/tschRefPointNoWidthRW_71.root'\
    --data-config    HadronicSMEFT/data/delphesJet_ctWRe_weighttest.yaml\
    --network-config HadronicSMEFT/networks/ParticleNetDef_likelihoodFree.py\
    --model-prefix ctWRe_lin_quad\
    --batch-size 10  --start-lr 5e-3 --num-epochs 1 --optimizer ranger\
    --log HadronicSMEFT/logs/train.log\
    --regression-mode\
    --weighting\
    --tensorboard test\
    --gpus 0
